version: '3.4'

services:
  web:
    image: ${DOCKER_REGISTRY-}web
    build:
      context: .
      dockerfile: src/Web/Dockerfile

  microservice:
    image: ${DOCKER_REGISTRY-}microservice
    build:
      context: .
      dockerfile: src/Microservice/Dockerfile

