version: '3.7'

services:

  demosite:
    image: ${DOCKER_REGISTRY-}demosite
    build:
      context: .
      dockerfile: src/DemoSite/Dockerfile

  microservice:
    image: ${DOCKER_REGISTRY-}microservice
    build:
      context: .
      dockerfile: src/Microservice/Dockerfile