version: '3.7'

services:

  demosite:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6100:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  microservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6200:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro